### ISSUE TITLE
Decide upper-bound on number of topics and minimum salience level from Rosette API

### ISSUE THREAD

**Issue by wonderchook** [wikimedia/phoenix#71]
May be help from API on this: https://support.rosette.com/hc/en-us/articles/360040847191-Understanding-Rosette-Confidence-Scores

**Comment by eevans** [comment]
Leveraging Cunningham's Law, #88 limits the number of Rosette topics to 10, and the minimum salience to .1

There are currently no provisions for a limit and/or offset when displaying a Node's _keywords_ attribute (aka related topics).

This is easily altered (prior to the planned Big Import™, anyway)

/cc @dianamontalion @mooeypoo @wonderchook

**Comment by eevans** [comment]
> Leveraging Cunningham's Law, #88 limits the number of Rosette topics to 10, and the minimum salience to .1
> 
> There are currently no provisions for a limit and/or offset when displaying a Node's _keywords_ attribute (aka related topics).
> 
> This is easily altered (prior to the planned Big Import™, anyway)
> 
> /cc @dianamontalion @mooeypoo @wonderchook

No one has suggested any changes to the values proposed above, so I'll close this issue now.  Feel free to reopen, or submit a new issue if you feel they should be changed.
